### ISSUE TITLE
Request for Moons of Peril luck

### ISSUE THREAD

**Issue by swirle13** [peanubnutter/collection-log-luck#11]
Hoping to get moons of peril drops added to this. Currently wanting to see how lucky I am with my current collection log. Thank you, love the plugin!

**Comment by peanubnutter** [comment]
Thanks! Sorry, just saw this today. I've been thinking about how to do this. The math is a little bit hard because of the way it works - you're guaranteed to get 1 of each piece, and then after completing a set, I think it goes back to "normal" random drops. And wiki says there's a "slight" preference for drop order (helm before weapons, etc.), but it doesn't clarify what that means, so I can't include that in the calculation.

If I figure out how to do this, then I think I can also add abyssal bludgeon pieces and pyromancer outfit, among others...

**Comment by peanubnutter** [comment]
Added support in the most recent update. Should be live eventually, whenever Runelite accepts it. Sorry for the wait.
