### ISSUE TITLE
Shared clue rewards possibly bugged?

### ISSUE THREAD

**Issue by gxgx55** [peanubnutter/collection-log-luck#7]
This cannot possibly be right.
Regular:
![image](https://github.com/peanubnutter/collection-log-luck/assets/22421149/7a4afaab-16da-46b0-89bd-32d80781830b)
DryCalc:
![image](https://github.com/peanubnutter/collection-log-luck/assets/22421149/2d189512-c7d7-49fa-90b1-c866d420e355)

All of the 100% items spit out absurd percentages when clicked
![image](https://github.com/peanubnutter/collection-log-luck/assets/22421149/e92fb521-e5f0-4049-8d8a-4b3e5b4e9c3c)

RSN: gxgx55 if you want to check the log for yourself

**Comment by jackemerson** [comment]
Definitions might be missing the (average) rolls per clue opened, in the definitions.

https://github.com/peanubnutter/collection-log-luck/blob/15eb4fda1575956c396d6fb74643586f7c59da94/src/main/java/com/peanubnutter/collectionlogluck/luck/LogItemInfo.java#L1843-L1850

`RollInfo` defaults to 1 roll (`rollsPerKc`) when not given an initial value, so all shared rewards would be calculated as one roll per clue opened, instead of the average (which is used elsewhere in the code), i.e., 
Tier | Avg.
-- | --
Easy | 3
Medium | 4
Hard | 5
Elite | 5
Master | 6

<details>
<summary>Rolls per Casket</summary>

Tier | Min | Max | Avg.
-- | -- | -- | --
Easy | 2 | 4 | *3*
Medium | 3 | 5 | *4*
Hard | 4 | 6 | *5*
Elite | 4 | 6 | *5*
Master | 5 | 7 | *6*

</details>

<details>
<summary><code>RollInfo</code></summary>
<p>

https://github.com/peanubnutter/collection-log-luck/blob/6ff547a41a49478db2cd39552e66e5f73176a9b7/src/main/java/com/peanubnutter/collectionlogluck/luck/RollInfo.java#L11

https://github.com/peanubnutter/collection-log-luck/blob/6ff547a41a49478db2cd39552e66e5f73176a9b7/src/main/java/com/peanubnutter/collectionlogluck/luck/RollInfo.java#L17-L21


</p>
</details> 

That looks to be the cause—though I've not looked to see if this is calculated later.

I guess the correct definition, for this example, would be:

  ```java
 public static LogItemInfo GUTHIX_PAGE_1_3835 = new LogItemInfo("Guthix page 1", 3835, 
         new PoissonBinomialDrop(ImmutableList.of( 
                 new RollInfo(LogItemSourceInfo.MASTER_CLUES_COMPLETED, 1.0 / 702.6, 6), 
                 new RollInfo(LogItemSourceInfo.ELITE_CLUES_COMPLETED, 1.0 / 77, 5), 
                 new RollInfo(LogItemSourceInfo.HARD_CLUES_COMPLETED, 1.0 / 650, 5), 
                 new RollInfo(LogItemSourceInfo.MEDIUM_CLUES_COMPLETED, 1.0 / 818.4, 4), 
                 new RollInfo(LogItemSourceInfo.EASY_CLUES_COMPLETED, 1.0 / 864, 3) 
         ))); 
```

**Comment by peanubnutter** [comment]
Crap, I just saw this. So sorry about that. I have multiple accounts and apparently this one is in charge of this project, not sure why.

**Comment by peanubnutter** [comment]
Alright, I think I got all of the locations fixed. That hurts. I can't believe that nobody that tested the plugin for me noticed, that my fairly extensive unit tests didn't catch it, and that my accounts have too low KC to really notice anything is off. I had like 0 clues done on the test account, lol.

Thank you very much for the reports!
